site_name: PatFolio
repo_url: https://github.com/PatrickAmbrosso/PatFolio
repo_name: PatrickAmbrosso/PatFolio
theme:
  name: material
  # logo: assets/Patrick-Ambrose-Logo.png
  favicon: assets/Patrick-Ambrose-Favicon.png
  icon:
    logo: material/alpha-p-box
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.path
    - navigation.top            #
    # - toc.integrate           # TOC inside navigation
    - toc.follow                # TOC follows scrolling
    - search.suggest
    - search.highlight
    - content.tooltips
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: deep purple
      accent: amber 
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode    
      primary: deep purple
      accent: amber

extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:patrickambrosericky@gmail.com
      name: Mail Patrick Ambrose
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/patrickambrosso/
      name: Patrick's Instagram Profile
    - icon: fontawesome/brands/github
      link: https://github.com/PatrickAmbrosso
      name: Patrick's GitHub Profile
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/PatrickAmbrosso
      name: Patrick's Twitter Profile
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/PatrickAmbrosso/
      name: Patrick's LinkedIn Profile

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html
  - abbr

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: |
  &copy; 2023 <a href="https://github.com/PatrickAmbrosso"  target="_blank" rel="noopener">Patrick Ambrose (PatrickAmbrosso)</a>


nav:
  - Home: index.md
  - Patrick.exe:
      - About: site-navs/about-me.md
      # - Projects: projects.md
      # - Skills Stack: skills-stack.md
      # - Work: work-experience.md
      # - Certifications: certifications.md
      # - Education: education.md
      # - Hobbies: hobbies.md
  - Digital Garden:
      - Welcome to the Garden: notes/garden-gate.md
      - Technology:
          - Docker: notes/docker.md
  - Contact:
      - Get in touch: site-navs/contact.md