# Site Details
site_name: PatFolio
site_description: Personal portfolio and digital garden of Patrick Ambrose
site_author: Patrick Ambrose
site_url: https://patrickambrose.com

# Github Repository details
repo_name: PatrickAmbrosso/PatFolio
repo_url: https://github.com/PatrickAmbrosso/PatFolio

# Extra CSS & JS
extra_javascript:
  - Javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - Stylesheets/Extra.css

# Theme Configurations
theme:
  name: material
  # custom_dir: Overrides
  # logo: Assets/Patrick-Ambrose-Logo.png
  favicon: Assets/Patrick-Ambrose-Favicon.png
  font:
    text: Nunito Sans
    code: JetBrains Mono
  icon:
    logo: material/alpha-p-box
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.path
    - navigation.top
    # - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tooltips
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    # scheme: slate
    # primary: purple
    # accent: deep purple
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: grey
      accent: deep purple 
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode    
      primary: grey
      accent: deep purple

# Markdown Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - Includes/abbreviations.md
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html
  - abbr

# Plugins Activation
plugins:
  - search
  - open-in-new-tab


# Copyright Notice
copyright: |
  Copyright &copy; 2023 <a href="https://github.com/PatrickAmbrosso"  target="_blank" rel="noopener">Patrick Ambrose (PatrickAmbrosso)</a>

# Footer Social Links
extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:patrickambrosericky@gmail.com
      name: Mail Patrick Ambrose
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/patrickambrosso/
      name: Patrick's Instagram Profile
    - icon: fontawesome/brands/github
      link: https://github.com/PatrickAmbrosso
      name: Patrick's GitHub Profile
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/PatrickAmbrosso
      name: Patrick's Twitter Profile
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/PatrickAmbrosso/
      name: Patrick's LinkedIn Profile

# Site Navigation
nav:
  - PatFolio: index.md
  - About Me: About-Me.md
  - Digital Garden:
    - Welcome to the Garden: Notes/Garden-Gate.md
    - Technology:
      - Docker: Notes/Docker.md
      - Golang: Notes/GoLang.md
  - Projects:
    - MkDocs Documentation Site: Projects/MkDocs-Documentation-Site.md
  - Learnings:
    - Road to DevOps: Learnings/Road-to-DevOps.md
